name: first_project_flutter
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  camera_camera: ^3.0.0 #pagina de tirar foto
  get: ^4.6.6
  path_provider: ^2.1.2
  permission_handler: ^11.0.1
  cupertino_icons: ^1.0.2
  flutter_vision: ^1.1.4
  camera: ^0.10.6 #pagina de camera ao vivo
  image: ^4.3.0
  image_picker: ^1.1.2
  flutter_tts: ^4.1.0
  flutter_soloud: ^1.2.5
  vector_math: 2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/labels.txt
    - assets/model.tflite
    - assets/audio/
  #   - images/a_dot_ham.jpeg
